spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    username: root
    password: 60870736a
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/image_laboratory?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=FALSE
  thymeleaf:
    prefix: classpath:/templates
    cache: false
resources:
  static-locations: classpath:/static,classpath:/templates

upload:
  path: /opt/server/data/

prefix:
  python:
    ip: localhost
    port: 8000

mybatis-plus:
  global-config:
    db-config:
      table-underline: true
  configuration:
    call-setters-on-nulls: true
  mapper-locations: classpath*:com/teqgin/image_laboratory/**/xml/*Mapper.xml


face:
  detect:
    model: D:\code\finalDesign\sdk\faceEngine\models
    sdk: D:\code\finalDesign\sdk\faceEngine\Release\FaceEngineSDK.dll
server:
  port: 8080